version: "2.4"

services:
  db:
    image: mongo:4.2.23-rc1
    container_name: cultivariot_mongodb
    restart: unless-stopped
    ports:
      - 27018:27017
    volumes:
      - ./src/db/data:/data/db
      - ./src/db/configdb:/data/configdb
    environment:
      - MONGO_INITDB_DATABASE=CultivarIoT
  
  db-seed:
    build:
      context: ./src/db
      dockerfile: Dockerfile
    depends_on:
      - db

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cultivariot_node
    restart: always
    depends_on:
      - db-seed
    ports:
      - 3333:3333
    volumes:
      - .:/usr/src/app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
